name: Basic Workflow Pipeline

# Trigger the workflow on push or pull request to any integration/ branch
on:
  push:
    branches:
      - 'integration/**'
  pull_request:
    branches:
      - 'integration/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use the version specified in your .nvmrc or package.json, if applicable)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'  # Change the version to whatever you are using

      # Step 3: Run ./run install to install dependencies
      - name: Install Dependencies
        run: ./run install

      # Step 4: Run tests to execute the test suite
      - name: Run Test Suite
        run: npx vitest run --coverage.enabled=true
        
      # Step 5: Run ./run URL_FILE to process the environment variable (assumes URL_FILE is passed in as an environment variable)
      - name: Run URL_FILE Command
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          LOG_LEVEL: 2
          LOG_FILE: log.txt
        run: |
            echo "https://github.com/caolan/async" > URL_FILE.txt
            FILE_PATH=$(realpath URL_FILE.txt)
            ./run "$FILE_PATH"
            
      # Step 6: Start the backend server
      - name: Start Backend Server
        run: npm run start:backend &
      
      # Step 7: Wait for backend to be ready
      - name: Wait for Backend Server
        run: |
            echo "Waiting for backend to start..."
            sleep 30  # Adjust time if backend takes longer to start
            curl -f http://localhost:3000/api-docs || exit 1
        shell: bash     
      
      # Step 8: Start the frontend server
      - name: Build Frontend
        run: npm run build
    
      # Step 9: Check if everything is successful
      - name: Workflow Success Check
        if: ${{ success() }}
        run: echo "Both backend and frontend started successfully. Workflow passed!"