name: Deploy to EC2

on:
  push:
    branches:
      - integration/1.0  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LOG_LEVEL: 1                  # Set log level to 0
      LOG_FILE: "./logfile.txt"      # Define log file path
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy application to EC2
      run: |
        echo "${{ secrets.AWS_PEM_KEY }}" > new_aws_access.pem  # Write the PEM key from the secret to a file
        chmod 600 new_aws_access.pem  # Secure the key file
        ssh -o StrictHostKeyChecking=no -i new_aws_access.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
        if [ ! -d "461_Phase2" ]; then
          git clone https://github.com/AWV2804/461_Phase2.git
        fi
        pwd
        cd 461_Phase2
        echo "Switching to the integration branch"
        git checkout integration/1.0
        chmod +x deploy.sh
        export LOG_LEVEL=${{ env.LOG_LEVEL }}      # Set log level on EC2
        export LOG_FILE=${{ env.LOG_FILE }}        # Set log file path on EC2
        export GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}  # Set GitHub token on EC2
        echo $LOG_LEVEL
        echo $LOG_FILE
        echo $GITHUB_TOKEN
        git pull origin integration/1.0
        # Log the deployment process
        echo "Deployment started at $(date)" >> $LOG_FILE
        ./deploy.sh >> $LOG_FILE 2>&1  # Redirect output to the log file
        echo "Deployment finished at $(date)" >> $LOG_FILE
        EOF
